services:
  - type: web
    name: metiri-ai-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free 